apiVersion: v2
appVersion: latest
dependencies:
    -   condition: liferay-aws-backup-restore.enabled
        name: liferay-aws-backup-restore
        repository: file://./charts/backup-restore
        version: 0.1.0
    -   name: liferay-default
        repository: file://../default
        version: 0.1.5
description:
    Liferay is an all-in-one DXP, LCAP, and Commerce platform. This chart is optimized for AWS.
icon: https://www-cdn.liferay.com/documents/d/guest/liferay-logo
name: liferay-aws
type: application
version: 0.1.6