apiVersion: v2
appVersion: latest
description:
    Liferay is an all-in-one DXP, LCAP, and Commerce platform. This chart provides cloud infrastructure resource definitions to support Liferay cloud native infrastructure.
icon: https://www-cdn.liferay.com/documents/d/guest/liferay-logo
name: liferay-aws-infrastructure-provider
type: application
version: 0.1.4