apiVersion: aws.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-70"
    name: default
spec:
    credentials:
        source: IRSA
---
apiVersion: kubernetes.m.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-70"
    name: default
spec:
    credentials:
        source: InjectedIdentity